### ISSUE TITLE
You have to be inside an ember-cli project in order to use the serve command.

### ISSUE THREAD

**Issue by stojankukrika** [eliyas5044/angular-laravel#3]
HI. Install npm and bootstrap@next, but when I run ng serve -o I get an error:

You have to be inside an ember-cli project in order to use the serve command.

How to solve this problem?

**Comment by eliyas5044** [comment]
@stojankukrika funny things bro ! you need to go root folder, then run this command

**Comment by stojankukrika** [comment]
@eliyas5044 I am run it in root bro. 
Here is solution for others who maybe have the same problem like I do:

```
npm uninstall -g @angular/cli
npm cache clean
npm install -g @angular/cli@latest
```

That is solve that problem.

TNX for your great start site.

**Comment by eliyas5044** [comment]
@stojankukrika Thanks for your comment :)
