### ISSUE TITLE
Problem with JSON.parse

### ISSUE THREAD

**Issue by henryonsoftware** [eliyas5044/angular-laravel#4]
I tried to create wrong case login or register but this app didn't show the error messages.
After some minutes diving in code, I saw that it is having error at ```const errors = JSON.parse(err.error);```

Error message:

![angular_error](https://user-images.githubusercontent.com/12124934/33362274-4459acfc-d50e-11e7-9c4b-b6ad595d69de.png)

Should replace with ```const errors = err.error;``` instead.
File need fix:
- book.component.ts
- login.component.ts
- register.component.ts

**Comment by eliyas5044** [comment]
@viethuongdev thanks for your feedback, i will try to fix that :)

**Comment by eliyas5044** [comment]
i updated code and fixed this problem. so closing it.
