### ISSUE TITLE
Endless Loop after Login

### ISSUE THREAD

**Issue by danboh** [eliyas5044/angular-laravel#5]
Thanks for this package, I've really learned lots about Angular with this.

However, I'm facing a frustrating situation, and I think it's related to the routing but unclear how to resolve it. After logging in, the app goes into an endless loop always trying to go back to /login and because the user is logged in, keeps checking and redirecting forever.

Is this an issue with the package or my implementation?

Thanks!

**Comment by eliyas5044** [comment]
@danboh thanks for your comment, i have to check it.

**Comment by danboh** [comment]
Found the error, and it had nothing to do with your code :)

Thanks!
